### ISSUE TITLE
infinite scroll leaves line break between old/new parts of loop

### ISSUE THREAD

**Issue by rconstanzo** [madwort/rconstanzo-wp-plugins#1]
should just carry on without a line break so:
(tab), which sees no beginning or end...

Meeting with:
This process (loop starts here).

Should turn in to:
This process, which sees no beginning or end...

**Comment by madwort** [comment]
Just added a patch that changes the style of the first <p> in the inserted content to be display: inline; which means that it flows up behind whatever's there already. Works on my demo page!
