### ISSUE TITLE
formatting for link dump (description list)

### ISSUE THREAD

**Issue by rconstanzo** [madwort/rconstanzo-wp-plugins#12]
```
<dl style="padding-left: 30px;">
  <dt><b>John Zorn</b></dt>
  <dd style="padding-left: 10px;"><a href="https://en.wikipedia.org/wiki/John_Zorn" target="_blank">-https://en.wikipedia.org/wiki/John_Zorn</a></dd>
</dl>
```

(markup gobbles up html so go into edit view to see)

This seems to work and look the best from what I've played with (note the "-" before the display name in the href)

Edit: you can use three backticks around raw html to display in github comments.

**Comment by madwort** [comment]
Closing & refiling on correct repo (this repo has the old WP plugin scraper, plan is to use the offline PHP5.4 scraper https://github.com/madwort/link_scraper )
