### ISSUE TITLE
tag cloud - have pointer turn into href-style "pointing hand"

### ISSUE THREAD

**Issue by rconstanzo** [madwort/rconstanzo-wp-plugins#15]
Hovering over tag cloud terms tuns into edit cross-hatch so its unclear that one should click on it.

Can just make them href style links so they take on css characteristics (though diff css (no underline, not pink))

**Comment by madwort** [comment]
Hmm, weird, they're HTML `<span>`s so use regular CSS (although you'd have to manually specify to do hover / underline / etc. Simple to change them to be `<a>`s. Will do this when possible.

**Comment by rconstanzo** [comment]
I've changed all the `<span>`s to `<a>`s and that takes on the CSS/look, but the pointer still stays as a 'text' one.

```
    <a class='tag'>composition</a>,
    <a class='tag'>improvisation</a>,
    <a class='tag'>performance</a>,
    <a class='tag'>diy</a>,
```

I also tried adding a cursor type to the containing `<div>` but that seemed to break the whole page.

```
<div style="cursor: pointer">
```

**Comment by madwort** [comment]
Fixed in https://github.com/madwort/rconstanzo-wp-plugins/commit/7fb4b41cff592454c5439e8907656b0d52710448

**Comment by rconstanzo** [comment]
Ah that's much simpler than the mess I was trying.

Still a 'text' pointer though.

**Comment by madwort** [comment]
Which browser? Turns to finger pointing for me in Safari with latest
version & css file.

**Comment by rconstanzo** [comment]
Safari 9.0.
Had updated all the bits yesterday but to be safe just deleted and reuploaded plugin and still 'text' pointer.

**Comment by madwort** [comment]
CSS was enabled in my test but not in the plugin. Should be fixed now!

**Comment by rconstanzo** [comment]
Bingo!
