### ISSUE TITLE
tag cloud - search query should come up in hover window

### ISSUE THREAD

**Issue by rconstanzo** [madwort/rconstanzo-wp-plugins#16]
The links should pop in hover window just like the RPPD styled one (translucent white rectangle)

**Comment by madwort** [comment]
Let me know how this one looks in context & we can do further tweaks

**Comment by rconstanzo** [comment]
This works but feels awkward where it is. I was picturing the size/placement of the RPPD hover (near the mouse pointer and smallish) as right now if you want to interact with a term on the top row you need to hover over it, then "dodge" the words on the bottom row while moving down to the actual links.

Is it possible to have a scrollable hover window? So the UX would be hovering over term to bring up window, then move into window area to either click on any terms, or scroll to view more matches. And then hovering away from the floating window makes it disappear again (again, like the RPPD hover). At the moment the search terms are "sticky", so it's unclear how to bring them up and make them go away.

**Comment by madwort** [comment]
Ok, to make this work I think they'll have to be buttons rather than just text, but if I make the buttons all white you won't be able to tell the difference... 

Also filing this for myself for later:

http://stackoverflow.com/questions/9707397/making-a-div-vertically-scrollable-using-css

---

Tom Ward
tomward@fmail.co.uk
07773576062

**Comment by rconstanzo** [comment]
Yeah that would be a good solution.

**Comment by madwort** [comment]
is that more like it?

**Comment by rconstanzo** [comment]
Yup that does it. I added a bunch of whitespace at the bottom of the jump so it doesn't grow/shrink each time you bring up a term.

Behold my elegant code, lol:
`<div style="line-height: 2000%;"><span style="visibility: hidden;">*</span></div>
&nbsp;`
