### ISSUE TITLE
Tag Cloud parser not searching whole page

### ISSUE THREAD

**Issue by rconstanzo** [madwort/rconstanzo-wp-plugins#17]
Same issue as link scraper(?):

most evident on the long blog posts by checking links/vids towards the bottom of page.

for example : http://johnlely.co.uk/ near the bottom of http://www.rodrigoconstanzo.com/2015/04/making-decisions-in-time/

or http://www.lcasserley.co.uk/ at the bottom of this : http://www.rodrigoconstanzo.com/2015/06/cut-glove/

**Comment by madwort** [comment]
Yes, will be the same issue as the link scraper...

**Comment by madwort** [comment]
Also, ignore content in the sidebar, eg. 

> `dfscore` is bringing up dozens of entries for `dfscore 2.0' which is on the sidebar widget of every single webpage

**Comment by madwort** [comment]
See also https://github.com/madwort/link_scraper/issues/4

**Comment by rconstanzo** [comment]
As long as you've run it again, this should be done/closed.

Once I get the notes back from my proofreader I may edit a few bits of text here or there, so there's a tiny chance the tagcloud parser might need to be run again, but very unlikely.

I'll leave this open for you to close, in case the parser still needs to be run again.

**Comment by rconstanzo** [comment]
Should I just check to see if the links are all good, or is there a(nother) technical thing happening here still?

**Comment by madwort** [comment]
Yep, I think errors of omission are fixed but there are still errors of commission to tweak away.

**Comment by madwort** [comment]
Hey man,

Could you compare the attached tag data file run through a different parsing mechanism to the one that’s in the repo? Should have removed the sidebar links (eg. dfscore) but might have introduced some weirdness..

Cheers,

Tom

**Comment by madwort** [comment]
Actually, easier to compare if the CSV files are sorted - contrast these two…

**Comment by rconstanzo** [comment]
Weird, there are more entries in the old one. It's hard to compare them side by side as most of it is duplications, then there are odd things that are in the new one (that don't appear to be in the old one), but under a closer look it looks like they are there, but in a diff order.

For example:
48 in both is the same.
44 in the new one doesn't appear to be in the old one, BUT it is there, just at 40.
45 in the new one is at 80 in the old one.

The new parser also has a bunch of the crazy characters (which it could be coincidental, but the funky character ones appear to vary/differ in old/new). Things like `Iâ€™ve` and `analyses.Â A fellow` and `anÂ Upright`.

Could the unicode character thing be responsible for weirdness here?

**Comment by rconstanzo** [comment]
I think this bug is closed enough to be closed. The funky characters don't show up in the hover window, so it's fine, and there are more entries than the previous one, so I think it's working well enough.

**Comment by rconstanzo** [comment]
In being thorough, it seems like it searches outside of the main body as it's pulling up terms in the comment section! I noticed that "behaviour" was a tracked thing and went to fix my spelling to US spelling only to notice that it was in the actual comment section, hehe.

I've just removed the UK spelling from the TCdata thing.

**Comment by rconstanzo** [comment]
I've updated the terms. Can you have it dump another `tag_cloud_data.csv`?

**Comment by madwort** [comment]
Just re-done the dump, was looking at using another parser but that still has some charset issues & I think now that the contents of your sidebar have changed the number of false-positives has gone down so I'm going to just stick with the existing one.

**Comment by rconstanzo** [comment]
Yeah was about to post that a bunch of the funky `A` type characters were still in there. Will test this one now.

**Comment by rconstanzo** [comment]
Have you pushed the new dump? Last one I have is from 30min ago.

**Comment by rconstanzo** [comment]
Posted it in a text, but might as well put it here so everything is in one place. I hadn't updated the `link-scaper` repo version of `tag_cloud_data_compile.php`. The "current" version of it is the one that's in `tag_cloud_data` (in the main `wp plugins` repo).

Just pushed the change to it, but noticing some other stuff in that file, so reverted and repushed just the `$keywords` bit.

**Comment by madwort** [comment]
Ah, ok, so, it's a `UTF-8` charset file, if you look at it with a program that thinks it's an `ISO-8559-1` file, you'll see `Å` characters all over the place, but the file is actually correct. Try opening it in TextMate & see if they go away and/or try uploading it to the webserver & trying it in place. I have had some issues with the parser in `link_scraper` doing conversions back & forth between charsets & making these chars impossible to get rid of, but the definitive parser for now that I'm using is the one in this project (rconstanzo-wp-plugns).

**Comment by madwort** [comment]
(I'm looking at the data file that's currently in git & it looks right to me here & on my local webserver)

**Comment by rconstanzo** [comment]
At the moment they only show up in the tag cloud hover window, and only the `Å` characters (lower case ones too).

Is the weirdness in the datafile or the wordpress source files?
Rather, are you suggesting I go through the `data.csv` file or the wordpress posts?

**Comment by madwort** [comment]
damn, I was sure this was right, just done another dump & pushed

**Comment by rconstanzo** [comment]
The body of christ compels you...
