### ISSUE TITLE
first time infinite scroll loops it leaves a gap

### ISSUE THREAD

**Issue by rconstanzo** [madwort/rconstanzo-wp-plugins#2]
(markdown swallows code/div/p stuff, edit to view)

possibly due to <div>/<p> in shortcode

<p>This process<div id='scroll-to-read'><p></p></div>

This process

, which sees no beginning or end, is presented [frozen, paralyzed, sanitized, cauterized] as a snapshot here. The work is made up of a network of compositions, videos, recordings, software, scores, performances, and improvisations which all interrelate and feed into each other. Each individual component rarely stands alone, or has clear temporal boundaries.

**Comment by madwort** [comment]
Yes, so this snippet of text should move inside the looping <div>. There's two obvious ways to fix this. First is:
- add a parameter to the shortcode that species the text to pre-load the first loop in the right place (eg. [infinite-loop text="This process"])

Second is:
- Embed the relevant HTML snippet directly in the page & remove the shortcode completely.

Maybe the first is going to be more reliable?

**Comment by rconstanzo** [comment]
this works gangbusters. 

the absolute sexiest option would be for the parameterised 'text' to not fade in, but remain solid (so "This process" is preloaded, and does not disappear/fade in with the rest of the text). 
but that's really reaching for perfection.

**Comment by madwort** [comment]
Hmm, will note that as a feature request, but not sure if it'll make the cut.
