### ISSUE TITLE
RPPD - include key for pieces/software/concept

### ISSUE THREAD

**Issue by rconstanzo** [madwort/rconstanzo-wp-plugins#20]
In the top right having some kind of legend/key:

pieces = <pink square>
software = <green square>

**Comment by madwort** [comment]
Currently the difference is just the narrow border of the circle - should this be a wider border? Should the popup change colour to match this border?

**Comment by rconstanzo** [comment]
The border is fine, though I may make it a touch bigger.

It's more having a little legend in the top right of the main div to know what green/pink/etc.. mean.

Like this:
http://i.stack.imgur.com/7Tk8n.png

**Comment by madwort** [comment]
(Nb. position can be configured by tweaking `x`, `cx` & `y` variables in this block !) https://github.com/madwort/rconstanzo-wp-plugins/blob/master/restructuring_piece_project_diagram/restructuring-piece-project-diagram.js#L63-L80
