### ISSUE TITLE
RPPD - bigger buttons for categories (technical, temporal, aesthetic)

### ISSUE THREAD

**Issue by rconstanzo** [madwort/rconstanzo-wp-plugins#21]
Using the same button size/type as the improv analysis (big and spaced out)

**Comment by madwort** [comment]
Change here:
https://github.com/madwort/rconstanzo-wp-plugins/blob/master/restructuring_piece_project_diagram/restructuring-piece-project-diagram.css#L56

Perhaps by addng 'padding: 20px;' or similar?

**Comment by rconstanzo** [comment]
Bang. Done.

```
{
  border: 1px solid black;
  padding: 3px;
  padding-left: 7px;
  padding-right: 7px;
  color: black;
  background-color: #7CAAAC;
  margin: 0.5em 1em 0 0 ;
}
```
