### ISSUE TITLE
infinite scroll breaks when RPPD is in it

### ISSUE THREAD

**Issue by rconstanzo** [madwort/rconstanzo-wp-plugins#23]
I updated the chapter1.html source file for the infinite scroll thing:
http://rodrigoconstanzo.com/thesisfiles/chapter1.html

And when infinite scroll fills in, it jumps you on the page to where the RPPD would live (in the new iteration). I suspect this might have something to do with the RPPD div as if I insert two instances of RPPD into the regular text, they both pile up in the same place, regardless of where the 2nd instance was placed.

**Comment by madwort** [comment]
> I updated the chapter1.html source file for the infinite scroll thing:
> http://rodrigoconstanzo.com/thesisfiles/chapter1.html
> 
> And when infinite scroll fills in, it jumps you on the page to where the RPPD would live (in the new iteration). I suspect this might have something to do with the RPPD div as if I insert two instances of RPPD into the regular text, they both pile up in the same place, regardless of where the 2nd instance was placed.
> 
> Yep, the JavaScript discovers where to create the RPPD by looking at the unique id of the div - if it ain’t unique, it’ll do weird stuff. I can give it a unique id when the first instance in the page is created by the Wordpress plugin, but it might be slightly difficult to do when creating it through the infinite scroll. I’ll have to mull on what is a good solution.

**Comment by madwort** [comment]
Latest version needs testing in context.

**Comment by rconstanzo** [comment]
Getting a parsing error on lines 60/61/62 (I tried removing variations of the ')' but couldn't get it to work right.

`Parse error: syntax error, unexpected ')' in /var/www/clients/client1/web10/web/wp-content/plugins/RPPD-v0.4/restructuring-piece-project-diagram.php on line 60`
