### ISSUE TITLE
tag cloud - should filter out non-letter characters

### ISSUE THREAD

**Issue by rconstanzo** [madwort/rconstanzo-wp-plugins#24]
things like � and &#8221 are getting thrown into the displayed results of the tagcloud

**Comment by madwort** [comment]
> things like � and &#8221 are getting thrown into the displayed results of the tagcloud

I think this is due to charset issues in the script that generates the datafile. 
The server spits out `UTF-8` to my browser, but maybe php’s `file_get_contents` is requesting `ISO Latin 1` instead & it’s getting munged. 
Working on it…

**Comment by madwort** [comment]
Ah, this is my issue. http://stackoverflow.com/questions/2187615/utf-8-characters-in-preg-match-all-php
The easy solution - use PHP 6...

**Comment by madwort** [comment]
Actually, just enabling unicode mode correctly I think fixes the  � es. The `&#8221;` entities are still TODO...

**Comment by madwort** [comment]
I think this is now fixed - please verify & re-open if you still see problems.

**Comment by rconstanzo** [comment]
Working!

**Comment by rconstanzo** [comment]
Actually spoke too soon. Just found a I&#821 in dfscore and a &#8220 in gesture.
