### ISSUE TITLE
RPPD - just a composition/software/framework display flag

### ISSUE THREAD

**Issue by rconstanzo** [madwort/rconstanzo-wp-plugins#26]
Having a version of the chart that displays only those three node types (composition/software/framework), so only those node types show up, as well as the legend only displaying those too.

I would imagine there might need to be another type added to the connections.cvs for this display as it would be hard(?) to parse out the connections with concepts/groups/etc.. removed. The other display types (conceptual/aesthetic/technical) can just remove the nodes and only make connections with that's there.

**Comment by rconstanzo** [comment]
This works well, and it's really awesome seeing the reduced view of things.

The temporal view breaks (literally a gap in time). I can make a new type in the connections.csv so to simplify things, rather than trying to parse something else out of what's left.

**Comment by madwort** [comment]
Ah, yes, the temporal view has a problem. So, you'll add another type to the file that's like an alternate temporal view?

**Comment by rconstanzo** [comment]
Yeah I can just make a connection pathway that excludes the unused categories (so this would be "mode" 5).

So the temporal view of the reduced version would reference that bit only.

**Comment by rconstanzo** [comment]
Actually looking at it now, there's a couple of "compositions" that need to be removed from the second chart. They are in the full chart for context, but this section should just be the 'phd thesis submitted' compositions.

Can the 2nd chart just reference completely new data? (modes 5/6/7/8, in the same order), and I'll just manually pop things in/out.

**Comment by madwort** [comment]
But that wouldn't hide a composition itself - only its connections? 
I think we do need a new connection type for the just_csf temporal case, but I think all other connections should reuse the same data as before (as the reasons don't change?)
Then to hide a composition, maybe we should add a "phd_thesis" column to `blurbs.csv` with true/false, 0/1, phd/world, something?

**Comment by rconstanzo** [comment]
Ah that's a good point, and solution. Also removes potential redundancy stuff too.

With phd_thesis = 1 meaning it's visible in the 2nd (included in thesis) chart. So things I want left out would be set to phd_thesis = 0.

And mode = 5 will be the thesis temporal view (in `connections.csv`)

I'll dress up the documents when I get home today.

With the `blurbs.csv` file does it go by column name or placement? I cleaned it up a bit ago removing unneeded info, but I left unneeded columns in not to break anything.

**Comment by madwort** [comment]
I _think_ it goes by column name, so removing unused cols shouldn't break anything...

---

Tom Ward
tomward@fmail.co.uk
07773576062

**Comment by madwort** [comment]
Maybe rename just_csf to just_thesis too...?

---

Tom Ward
tomward@fmail.co.uk
07773576062

**Comment by rconstanzo** [comment]
Ok, I'll groom it. And that works for the just_thesis. I'll rename it in the inline shortcode.

**Comment by rconstanzo** [comment]
Ok, `just_thesis` and `phd_thesis` flags all working well.

Just removed an unused point in `connections.csv`, so that should all be groomed and ready.

(note to self, I should figure out how to reference commits in these comments)

5ef55a3cdffff94f35b2f080bc6c769a3edca164

**Comment by madwort** [comment]
(Note to self: remaining task is to use mode 5 for temporal connections in `just_thesis` mode)

**Comment by madwort** [comment]
Closed this ticket from git as I think I’ve done everything, but please double-check as there were several discrete things in this thread…

**Comment by rconstanzo** [comment]
Bang bang!
Yup that was it. 

Sorry, these threads got a bit messy with tangential problems.
