### ISSUE TITLE
Hover for connections on RPPD doesn't respond very well

### ISSUE THREAD

**Issue by madwort** [madwort/rconstanzo-wp-plugins#27]
It does kind of work, but it's a bit glitchy / tricky to trigger...

**Comment by rconstanzo** [comment]
Would this be as easy as making the hover area bigger than the actual connection line? (suggestion from my supervisor)

**Comment by madwort** [comment]
Yes in theory, but in practice the hover area is defined by the SVG element & because it's most generally useful on the web, transparent elements aren't hoverable (the hover goes to the element underneath)...

**Comment by madwort** [comment]
Giving it something like a white border would kind of work, but the borders would overlap - it's possible to do it by drawing a second set of white connection lines (also with hover) completely underneath the visible connection lines, but I'm trying to think of an easier way before I go to the trouble of that...

**Comment by rconstanzo** [comment]
That makes sense. This is kind of working, so definitely low priority (if at all).

**Comment by madwort** [comment]
Improved a bit, marked as closed for now. If necessary, have further ideas for improvement:
- increasing hover target size via a very long-winded method
- debouncing the hover handler

**Comment by rconstanzo** [comment]
Yeah that's perfect. 
It pops up immediately so you know it's something to interact with, which is the most important thing for the chart.

I added a bit of "instructions text" to the chapter anyways, saying how to interact, so that should make it more digestible anyways.
