### ISSUE TITLE
Tag Cloud search parsing full/partial terms

### ISSUE THREAD

**Issue by rconstanzo** [madwort/rconstanzo-wp-plugins#28]
There's a couple of terms that are ended up in searches weird.

"meta" is bringing up "metal". Thankfully I don't talk about metal very much, but it's weird having it in there.
It also brings up "metaphorical" and derivations of it.

Similarly "game" brings up "gamepad", which is another term in there, but they are used quite differently in the thesis.

The results for dfscore are also particularly weird. It's picking up a ton of partial matches. Oooh, I see what's happening, it's picking up the blog post in the sidebar called "dfscore 2.0". And that's on EVERY page. The same is surely happening for any terms that are in the sidebar.

I guess the parsing should be limited to what's in the body only then?

And it might be a case of storing up only exact matches instead of partial words (so "intro" doesn't bring up "introduction").

...
Also just caught that "form" brings up tons of "performed", which was confusing as that's a term in there too. I thought I had a tag mismatch somewhere.

**Comment by madwort** [comment]
Ok, I need to revamp the tag cloud data compiler widget to address #17 so will look at this at the same time... 

Will try out exact matches...

**Comment by madwort** [comment]
There's a special character for just that: 

http://regular-expressions.mobi/wordboundaries.html

I'll add it asap. 

---

Tom Ward
tomward@fmail.co.uk
07773576062

**Comment by madwort** [comment]
please test & comment!

**Comment by rconstanzo** [comment]
The word boundaries thing works well, but it's still searching the whole page (`dfscore` is bringing up dozens of entries for `dfscore 2.0` which is on the sidebar widget of every single webpage)

**Comment by madwort** [comment]
ok, will address ignoring the sidebar as part of getting the whole page working #17
