### ISSUE TITLE
RPPD hiding connections in temporal view

### ISSUE THREAD

**Issue by rconstanzo** [madwort/rconstanzo-wp-plugins#29]
I want to say that this was an older/fixed bug but didn't find it in the issues, maybe this was an 'email fix'.

When in the temporal view, the pop-up window shows the "Connections", but they are all empty (since there's no connection data for them).

**Comment by madwort** [comment]
Weird, I thought there was too...

---

Tom Ward
tomward@fmail.co.uk
07773576062

**Comment by rconstanzo** [comment]
This works, but the update flipped around the behavior for `[restructuring-piece-project-diagram just_csf=true]` That now shows the "full" version, and leaving out the `just_csf=true` part shows only the thesis stuff.

The 'inversion' of the shortcode doesn't matter so much as long as they reference the correct `phd_thesis` flag in the `blurbs.csv` file (which has been updated).
