### ISSUE TITLE
Infinite scroll whitespace/glitching

### ISSUE THREAD

**Issue by rconstanzo** [madwort/rconstanzo-wp-plugins#30]
The infinite scroll (since updating RPPD I think) is leaving a ton of whitespace on first loop. (so after "This process,").

It also jumps some (kind of like what it was doing when the RPPD couldn't be duplicated).

Actually, looking at the 2-node springy chart and It's doing what RPPD used to (duplicating in the same place each time). So I guess this is a more a bug with the springy-links than it is infinite scroll.

**Comment by madwort** [comment]
ok, might be that the springy chart has the same no-duplication issue as the rppd.

**Comment by rconstanzo** [comment]
This fixes the jumping thing but a different issue has emerged. Will open a new ticket for it as to not clutter this thread too!
