### ISSUE TITLE
IL - whitespace gap first time around

### ISSUE THREAD

**Issue by rconstanzo** [madwort/rconstanzo-wp-plugins#32]
(making each bug its own thread, even though this is likely the same issue as #31 )

The first time IL loops it puts a real big gap between the previous paragraph and the first paragraph of the loop.

![screen shot 2015-12-18 at 6 50 00pm](https://cloud.githubusercontent.com/assets/2747015/11904655/6232000c-a5b9-11e5-9c8d-3f78e4e28b90.png)

**Comment by madwort** [comment]
Some test-specific CSS was left in the production file. Removed!

**Comment by rconstanzo** [comment]
Sweetness.
