### ISSUE TITLE
IL - duplicate first chapter in loop

### ISSUE THREAD

**Issue by rconstanzo** [madwort/rconstanzo-wp-plugins#33]
Looks like the `<span>` thing isn't working right as it's duplicating the first paragraph when you loop.

Or am I supposed to leave out the first chunk of text altogether? (", which sees no beginning or end....").

This is what the loop point looks like:

`This process, which sees no beginning or end, is presented [frozen, sanitized, cauterized] as a snapshot here. The work is made up of a network of compositions, videos, recordings, software, scores, performances, and improvisations which all interrelate and feed into each other. Each individual component rarely stands alone, or has clear temporal boundaries.
, which sees no beginning or end, is presented [frozen, sanitized, flattened] as a snapshot here. The work is made up of a network of compositions, videos, recordings, software, scores, performances, and improvisations which all interrelate and feed into each other. Each individual component rarely stands alone, or has clear temporal boundaries.`

**Comment by madwort** [comment]
Yep, the first chunk is now in the plugin (or configurable), so remove completely from chapter1.html !

**Comment by rconstanzo** [comment]
Duh, that was it!
