### ISSUE TITLE
Tagloud - not jumping into thesis properly

### ISSUE THREAD

**Issue by rconstanzo** [madwort/rconstanzo-wp-plugins#34]
When clicking into the tag cloud, it pulls up an anchor link reference (`http://www.rodrigoconstanzo.com/thesis-introduction/#software,10`) but that doesn't seem to actually jump you into the thesis.

Here are some other random ones (that don't work):
`http://www.rodrigoconstanzo.com/thesis-introduction/#feedback,1`
`http://www.rodrigoconstanzo.com/thesis-introduction/#composer,0`
`http://www.rodrigoconstanzo.com/thesis-introduction/#game,2`

Tried it in Safari 9.0.2 and Chrome 47 and the same behavior.

**Comment by madwort** [comment]
Ok, so it's supposed to fire the jump instruction when the page is fully loaded, but it's doing it too soon so it can't find the place it's supposed to jump to. It works if I run it after a short delay, just figuring out the best way to minimise this.

**Comment by rconstanzo** [comment]
It's working for some, but not others. Maybe it's an issue with longer pages needing more a delay?

For example, this works for me:
`http://www.rodrigoconstanzo.com/2013/02/strikethrough-me-you-battle-pieces/#gesture,7`

However, these do not:
`http://www.rodrigoconstanzo.com/thesis-introduction/#improvised,0`
`http://www.rodrigoconstanzo.com/2015/04/making-decisions-in-time/#compose,0`
`http://www.rodrigoconstanzo.com/2015/06/cut-glove/#feedback,16`

**Comment by madwort** [comment]
yep, for me too. increasing the delay to see if that helps.

**Comment by rconstanzo** [comment]
Still not doing it for the long ones (intro and cut glove for example).

My desktop computer is quite slow and it's definitely an issue there, but testing it on my laptop, they still don't work. Even if I refresh the page in place.

Is the delay for when you click into the page and THEN it jumps to the point, or is the delay happen at another time? Or rather, does it effect UX or is it a parse-y thing that can just be made like 10s or something.

**Comment by madwort** [comment]
Yep, it'll affect UX but let's try 10 secs to see if it actually works, then we can reduce.

**Comment by rconstanzo** [comment]
Yup, working, just obviously really slowly, hehe. I'll try shrinking it down and seeing when it stops working.

**Comment by rconstanzo** [comment]
Some further testing. 3sec seems to work some of the time, but I noticed some stuff.

It looks like the further into the document it is the less likely it is to load (this could just be correlation and not causation though as I've not tested it super thoroughly) but stuff like this seems to work more than often:
`http://www.rodrigoconstanzo.com/2015/04/making-decisions-in-time/#meta,2`

But stuff like this (ie much further into the document) never comes up:
`http://www.rodrigoconstanzo.com/2015/04/making-decisions-in-time/#analysis,95`

It also seems like the pages with heavy chart stuff (intro and making decisions) seem to load slower. It took me a while before I could get the intro chapter to load something, but it finally did.

I also logged out of wp as it seemed like the grey bar at the top when you're logged in seemed to take a bit to load too. Not sure if that helped or not though.

I don't suppose there's a call to know once everything has fully loaded? (charts/js/d3, embeds, etc...)

**Comment by madwort** [comment]
The problem is - there is a call to know once everything has fully loaded, but we're currently waiting for this call _then_ waiting several seconds & still finding not everything's loaded...

**Comment by madwort** [comment]
Hmmmmmm

**Comment by madwort** [comment]
Just pushed a different way of attaching to the onload listener to make sure if that makes any difference - timeout reduces to 1sec to make testing easier.

**Comment by rconstanzo** [comment]
I think that does it. I've had one or two deep links in `Making decisions in time` not come up, but I can chock that up to this computer being slow as fuck, and Safari taking a shit into its mouth. (Seemed to work fine on Chrome on same computer).

Will test a little bit more, but I think this can be put to bed. (Will test it on my laptop)

**Comment by rconstanzo** [comment]
And that's a wrap.....

Time to close this issue, delete all local versions of the files, nuke the repo, format our computers, and take cyanide pills.

Wrapping up the editing on last video and then it's all done done...

**Comment by madwort** [comment]
OMFG

---

Tom Ward
tomward@fmail.co.uk
07773576062
