### ISSUE TITLE
RPPD should display connection data

### ISSUE THREAD

**Issue by madwort** [madwort/rconstanzo-wp-plugins#4]
This probably involves removing the code to draw different types of objects separately (and as different datasets) so that we can more easily link any object of any type to any other object of any type.

**Comment by madwort** [comment]
With this, I think it’ll help to have the actual connections that you want, or at least to mirror some of the patterns of connections, as this will help me to know how best to draw things. For instance, from looking again at your original designs, maybe you’ve grouped nodes & then connected one large group of nodes to another large group of nodes. Which is cool, but I need to decide whether to make it good-looking & convenient to do this, rather than just connecting individual nodes together (in which case you'd get a little forest of link lines between the two groups, which may be fine, but maybe doesn't look as good as it could).

I'm also thinking about whether this should be statically laid out, or whether we can do something that's more dynamic, derived from http://bl.ocks.org/mbostock/1062288 or http://bl.ocks.org/mbostock/1021953 . The second in particular, you can imagine clicking a button & suddenly the multiple gravity foci change to a different set & all the nodes fly around the screen.

**Comment by madwort** [comment]
With the first one, notice that we have a tree layout, so where you've grouped nodes, they'd have a parent node that has a connection to another parent node for this many-many connection.

**Comment by rconstanzo** [comment]
there's also something like this:
http://www.marccodina.com

where the info/text is displaced elsewhere.

im wondering/thinking if the connections themselves should have text. in some cases that will clarify things, but it might be clear enough without it. i presume this would effect some fundamental design issues though? (having or not having text).

as far as the connections. there will likely be some many-to-many things in there, as well as some circular stuff in one instance at least (hence the creation of two improvisation instances). there's a bit where it's a little feedback loop being shown, among other things.

actually in looking at these and playing with them more. the positions dont really need to change, especially if there’s a nice interface going on (like your first example, or marcs example above). the only tricky one is the temporal one, but perhaps that could just be a a single line running through them from first to last. meaning that the whole thing can just be a dynamic/moving d3-ish thing, with force movement stuff, that the thing moves/wiggles and things disconnect/reconnect based on the current view.

**Comment by madwort** [comment]
hmm, that's a great looking site & it works well with the info displaced. I think that could be good for your diagram, will experiment with that.

**Comment by madwort** [comment]
RPPD now revamped in a new direction, so closing this issue in favour of new issue to tweak the new design.
