### ISSUE TITLE
Infinite scroll preamble text doesn't disappear & fadein

### ISSUE THREAD

**Issue by madwort** [madwort/rconstanzo-wp-plugins#5]
Parameterised 'text' to not fade in, but remain solid (so "This process" is preloaded, and does not disappear/fade in with the rest of the text). 
(Might not make the cut)

**Comment by madwort** [comment]
Ok, fixed this. Needs a modification to your chapter1.html file to work correctly. The first element should be 

`<span>, which sees no beginning or end,...</span>`
Instead of:
`<p>, which sees no beginning or end,...</p>`

Then it should work.

**Comment by rconstanzo** [comment]
It kind of works but it does the opposite after a second. "This process" is there, then the rest of the text pops in (no fade), THEN "This process" fades in after that.

This is with the `<span>`-ed chapter1.html

**Comment by rconstanzo** [comment]
[vid_example.zip](https://github.com/madwort/rconstanzo-wp-plugins/files/67591/vid_example.zip)

**Comment by madwort** [comment]
Ok, next try - please remove the first `<span>` from chapter1.html - I've brought it into the plugin. It defaults to the correct text, but you can also override it from the shortcode as `text2` if you need. Let me know how you get on...

**Comment by rconstanzo** [comment]
Yup, perfect!

So badass looking!

**Comment by madwort** [comment]
:+1:
