### ISSUE TITLE
scroll/hover handler for springy-menu

### ISSUE THREAD

**Issue by rconstanzo** [madwort/rconstanzo-wp-plugins#6]
so when scrolling down page, or hovering over chapter, there's a bit of movement in menu

(lower priority)

**Comment by rconstanzo** [comment]
Nice! Working well.

It starts angling over if you scroll a lot, but it never "tips" over, so that's actually fine. And besides, no one is going to be on this landing page just sat there wiggle/jiggling the thing.

**Comment by madwort** [comment]
...you hope...

**Comment by rconstanzo** [comment]
Lol yeah. In playing with the tag cloud thing the page does jump around a bit, so I might play with the physics some to see if keeps the diamond shape orientation (1 top, 2 middle, 1 bottom, but at a slight angle).
