### ISSUE TITLE
2 node view of springy-menu

### ISSUE THREAD

**Issue by rconstanzo** [madwort/rconstanzo-wp-plugins#7]
showing just central two chapters (cut glove, making decisions) for use in 1st chapter text

(lower priority)

**Comment by rconstanzo** [comment]
Sike!

Super low priority this, but leaving it as just an enhancement for now.

**Comment by rconstanzo** [comment]
This works but I think the height needs to change in the 2 node version (maybe down to 200px from 400px) as otherwise the nodes are just floating in an ocean of whitespace.

**Comment by madwort** [comment]
Should be fixed in 586acdab7f46ce57adbb0489c398e215525b66db please test

**Comment by rconstanzo** [comment]
Spot on.
